### ISSUE TITLE
Android N can't store the capture image

### ISSUE THREAD

**Issue by vjsystematix** [Xamarians/Xamarians.CropImage#7]
In android N devices, the image is not captured and throwing a error FileUriExposed exception due to this image is not saved in the local storage.

**Comment by Xamarians** [comment]
hi @vjsystematix,

I have tested this on android nougat the issue is not there, something else is causing this issue(hoping that you have already given the read-write storage permission).
[Here](https://developer.android.com/reference/android/os/FileUriExposedException) is some reference you can take and provide us some more details.
